### PR TITLE
Metro Hero Fix, Added off hours ability

### PR DESCRIPTION
**Pull request by scottiegarcia**
Made a few improvements off of your fork.
 - Fixed the issue with metro hero. Their responses are needlessly big, so I truncate them to avoid memory leak.
 - Added off hours ability. Have to update the readme still to include instructions on setting up the access key for getting the current time
 - Opted to just use `minutesAway` from Metro Hero for consistency. The `Min` field seems to just be rounded anyways.
 - Also included the updates to the head repo that you're missing so this can eventually be merged with that

### CODE REVIEW

**Comment by cjk314** [comment]
Hi! Thank you so much for this fork. Forgive me if this is the wrong place for this question—I'm new to Github and still learning.

Is it possible to update this fork with the changes [ScottKekoaShay](https://github.com/ScottKekoaShay) [mentioned yesterday in this post](https://github.com/metro-sign/dc-metro/issues/10#issuecomment-1475353628)? Specifically the CiruitPython 8.0.4 libraries and the ability to flip between platforms? Ideally the resulting code would allow platform-flipping (in Scott's code) _and_ adjustments for walking distance (in your code). Thank you for considering.

**Comment by erikrrodriguez** [comment]
Sure, I just pushed it. I made it an option because it's not personally useful to me, but you can set a second train group in the config.py file below the first train group. You must set the `swap_train_groups` variable to True if you wish to see it on the board.

Also updated libraries to version 8.

**Comment by rnelsonee** [comment]
Thank you @erikrrodriguez — I just found out about this project (hardware is on its way) and love that you merged the best features together. I might see if I can get a 2-board (128 x 32) option in there (like [in this project](https://github.com/kenschneider18/rpi-metro-display)) just to contribute something.

**Comment by MBrazda** [comment]
The MatrixPortal 4 seems to choke when copying the project files: ~200k too large for the storage space.  I haven't seen a solution for this, unless I'm copying more than required to run.  What did I screw up?

**Comment by erikrrodriguez** [comment]
That also happened to me once. I'm not sure what fixed it. But this last cycle I 

1. Flashed to the new CircuitPython version
2. Deleted each lib folder/file one at a time and replaced them once at a time 

and didn't have any issues. I'm assuming you are copying the same files that are in the lib.zip on this repository and not all of the available libraries from the Adafruit website.

I also generally unzip the file on my local harddrive and copy each to the board individually.

**Comment by MBrazda** [comment]
That's correct, just the files in the lib.zip repository.  I've been attempting copies in bulk, though, so I'll try a few iterations of 'file by file' and see if I can get it to work--or try by command line, I've been using the 'Finder' to copy.  Using CircuitPython 8.0.4 currently, but have not tried 'an older version' as some have said helps, nor the new 8.1.0 beta.  I'll have time tomorrow to troubleshoot a bit.  Thank you for the reply!  Much appreciated, sir.

**Comment by MBrazda** [comment]
Still having zero success, despite countless trial-and-error iterations.  It's entirely possible that I'm missing something very basic, but I've attempted the following with the consistent result of a blank screen with double red blinks from the Matrix Portal M4 status led.  Editing config.py with Mu Editor (not editing any other files at all.  
 - Tried CIRCUITPY firmware loads 6.2.0, 7.2.0, 8.0.4, and 8.1.0b0
 - Copied original "lib" from the original metro-sign/dc-metro, adding the additional 5 files to the root w/edited config.py
   -- No copying/space issues, but no success with execution
 - Copied ScottKekoaKay's branch, but no success
 - Copied (attempted) your "lib" files using both Finder and Terminal after disabling Mac indexing on the external drive
   -- Not enough space to copy full set of "lib" files (confirm there are significantly more files in your set than the original)
   
I haven't yet figured out how to troubleshoot the REPL serial output in Mu Editor, but was hoping to see if I could determine why it's failing. :(
CIRCUITPY Files - Neo v1

**Comment by erikrrodriguez** [comment]
Sorry to hear you are still having issues :( file structure looks right to me.

If you haven't, definitely open up the Mu Editor, plugin in your board, and hit the Serial button and see if anything appears in the output. If you're getting two red blinks, an exception code should be printed there.

Is there anything strange in your boot_out.txt file? I found this thread with links to the troubleshooting docs (which I'm assuming you've seen) but also a flash eraser utility.

It's also possible you could just have a bad board.

**Comment by MBrazda** [comment]
I did that in Mu Editor on two different computers and no traffic on the serial port, and nothing strange in the boot_out.txt file.  So weird.  The board worked fine in “sand table mode” or whatever when it first arrived, so I don’t think it’s bad.  Sent from my iPhoneOn Mar 27, 2023, at 19:59, Erik Rodriguez ***@***.***> wrote:﻿
Sorry to hear you are still having issues :( file structure looks right to me.
If you haven't, definitely open up the Mu Editor, plugin in your board, and hit the Serial button and see if anything appears in the output. If you're getting two red blinks, an exception code should be printed there.
Is there anything strange in your boot_out.txt file? I found this thread with links to the troubleshooting docs (which I'm assuming you've seen) but also a flash eraser utility.
It's also possible you could just have a bad board.

**Comment by rnelsonee** [comment]
I'm no expert, as I just learned about Mu yesterday. But I would re-seat the board and power (I had a loose connection so the sand demo was a bit wonky at first). Then I'd delete the files from the volume, and make sure the serial interface is working. Upon power up, open Mu → Serial and type `1+1` in the terminal to see if you get `2`. Then with the Mu editor save a code.py or main.py with just

`import time`
`while True:`
`    print("hello")`
`    time.sleep(1)`

And depending on how that goes, troubleshoot the board or more code. I just did a test and it seems line endings shouldn't be issues (Windows CR/LF vs LF) but it might be worth trying a different environment/OS.

**Comment by MBrazda** [comment]
Thanks, Erik—I will absolutely try that next. At least this gives me tan excuse to spend a little time diving deeper…if it had worked first attempt, I probably wouldn’t have taken the time to learn any more. Lazy. ;)I’m traveling for a few days, will reattack this weekend. Thanks again.Sent from my iPhoneOn Mar 27, 2023, at 22:38, Rick Nelson ***@***.***> wrote:﻿
I'm no expert, as I just learned about Mu yesterday. But I would re-seat the board and power (I had a loose connection so the sand demo was a bit wonky at first). Then I'd delete the files from the volume, and make sure the serial interface is working. Upon power up, open Mu → Serial and type 1+1 in the terminal to see if you get 2. Then with the Mu editor save a code.py or main.py with just
import time
while True:
    print("hello")
    time.sleep(1)
And depending on how that goes, troubleshoot the board or more code. I just did a test and it seems line endings shouldn't be issues (Windows CR/LF vs LF) but it might be worth trying a different environment/OS.

**Pull request merged**
